# src/embeddings/local_embedder.py

from typing import List
from .base_embedder import BaseEmbedder
from config.embedding_config import LocalEmbeddingConfig
from shared_libs.utils.logger import Logger
import fastembed

logger = Logger.get_logger(module_name=__name__)

class LocalEmbedder(BaseEmbedder):
    def __init__(self, config: LocalEmbeddingConfig):
        self.model = fastembed.TextEmbedding(
            model_name=config.model_name,
            cache_dir=config.cache_dir,
            local_files_only=True
        )
        logger.info(f"LocalEmbedder initialized with model '{config.model_name}'.")

    def embed(self, texts: List[str]) -> List[List[float]]:
        try:
            embeddings = self.model.embed(texts)
            if not embeddings:
                logger.error("No embeddings generated by local model.")
                return [[] for _ in texts]
            # Assuming fastembed returns a NumPy array or similar
            return [embedding.tolist() for embedding in embeddings]
        except Exception as e:
            logger.error(f"Error during local embed: {e}")
            return [[] for _ in texts]
