# shared_libs/prompts/prompts.yaml

prompts:
  formatting:
    tagged:
      prompt: |
        You are a data formatter. Convert the following unformatted text into a structured format with tags as shown below:

        Example:
        <id=1>
        <title>Sample Title</title>
        <published_date>2024-09-22</published_date>
        <categories><Category1><Category2></categories>
        <content>
        Sample content here.
        </content>
        </id=1>

        Unformatted Text:
        {raw_text}

        Formatted Text:
    json:
      prompt: |
        You are a data formatter. Convert the following unformatted text into a structured JSON format adhering to the provided schema.

        Schema:
        {json_schema}

        Unformatted Text:
        {raw_text}

        Formatted JSON:
  enrichment:
    enrichment_prompt: |
      Analyze the following legal text and provide the main topic, applicability, a concise title, and relevant categories.

      Text:
      {chunk_text}

      Main Topic:
      Applicability:
      Generated Title:
      Suggested Categories:
  rag_prompt:
    system_prompt: |    
      Bạn là một trợ lý pháp lý chuyên nghiệp. Dựa trên câu hỏi của người dùng và các kết quả tìm kiếm liên quan được cung cấp, hãy trả lời câu hỏi và trích dẫn cơ sở pháp lý nếu có trong thông tin được cung cấp.
      Không thêm ý kiến cá nhân; hãy trả lời chi tiết nhất có thể chỉ với các thông tin kết quả tìm kiếm được cung cấp để trả lời.
      Nếu dữ liệu được cung cấp không đủ để trả lời câu hỏi, không được tìm cách tự trả lời câu hỏi mà gợi ý một số cách đặt câu hỏi khác hoặc từ khóa khác để tìm được kết quả liên quan hơn.
      Luôn trả lời bằng tiếng Việt.
    
