version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  query_rag_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/query_rag.log
  shared_libs_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: logs/shared_libs.log
loggers:
  query_rag_logger:
    level: DEBUG
    handlers: [console, query_rag_file_handler]
    propagate: no
  shared_libs_logger:
    level: DEBUG
    handlers: [console, shared_libs_file_handler]
    propagate: no
root:
  level: INFO
  handlers: [console]
