type: object
properties:
  record_id:
    type: string
  title:
    type: string
  published_date:
    type: string
  categories:
    type: array
    items:
      type: string
  content:
    type: string
required:
  - record_id
  - title
  - content
pre_process_requirements: |
  - Remove any content that contains Personally Identifiable Information (PII).
  - Remove any part of the text that is not directly related to the title, particularly remove all promotional texts.
  - If possible, rephrase the title so that it better generalizes the content inside the content part.
  - If possible, remove all irrelevant, incoherent, or badly formatted texts inside the content part.
  - Always uses Vietnamese, except for the JSON properties itselves.